### PR TITLE
Conditionally include function declarations

### PR DESCRIPTION
**Pull request by davidakerr**
Without these I could not compile the project.

### CODE REVIEW

**Review by fbiego — COMMENTED** [review]
This is strange because the function declarations are already present in the respective watchface header files

**Comment by davidakerr** [comment]
> This is strange because the function declarations are already present in the respective watchface header files

I think it was due to differing face enable pragmas across [SDL2](https://github.com/fbiego/esp32-c3-mini/blob/main/hal/sdl2/app_hal.h#L23-L30) and [ESP32](https://github.com/fbiego/esp32-c3-mini/blob/main/hal/esp32/app_hal.h#L8-L15).

Would this solution be better ?

**Review by fbiego — COMMENTED** [review]
Maybe you can provide what error you got when compiling

**Review by fbiego — CHANGES_REQUESTED** [review]
I have identified the issue, looks like the new watchface header files were not included in ui.c

The corresponding headers files need to be included just like the other watchfaces

https://github.com/davidakerr/esp32-c3-mini/blob/4ea9db98d9b4246dea4b4bdf311465d7cc53d047/src/ui/ui.c#L9C1-L20C45

**Review by fbiego — APPROVED** [review]
awesome, thanks for the update

**Comment by davidakerr** [comment]
> awesome, thanks for the update

Thanks the help and for the great repository.

**Pull request merged**
